### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by ladar** [oldpatricka/vagrant-xhyve#8]
Someone is [asking](https://github.com/lavabit/robox/issues/21) me to publish xhyve versions of my vagrant boxes. It seems like adapting my existing qemu/libvirt configs, to create xhyve wouldn't be that hard... but of course there is no point, if the project is dead?

Packer support for xhyve would also be nice. Any idea if somebody has implemented a packer plugin to do that yet? Or is there a generic script/process I can apply to all of the boxes in my stable?

**Comment by oldpatricka** [comment]
As far as I know, it still works, but I don’t use the project that frequently. Packer support for xhyve would I feed be nice, but I have no plans at this point to implement it. 

If something is broken or you need help building an image let me know

**Comment by ladar** [comment]
@oldpatricka I try and avoid using MacOS, so it's wouldn't be for me personally. And without an active community to test the boxes, and provide feedback, there doesn't seem much point in publishing images. 

I can't make any promises, but if anybody takes over development, send them my way.
